use_frameworks!

platform :ios, '14.0'

target 'MuxStatsAliPlayer_Example' do
  pod 'MuxStatsAliPlayer', :git => 'https://github.com/mlytics/mly-stream-mux-ios-aliplayer.git'
   
  pod 'Mux-Stats-Core', '~> 4.5'
  pod 'AliPlayerSDK_iOS', '5.5.6.0'
end
